name: NeoKernel Builder

on:
  push:
  pull_request:
    branches: [ master ]
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: for aarch64
      run:  |
        sudo apt-get -y install gcc-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo apt-get -y install python2 ccache && mkdir -p ../PLATFORM/prebuilts/gcc/linux-x86/aarch64 && git clone  https://github.com/djb77/aarch64-linux-android-4.9 ../PLATFORM/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
    
    - name: Make G9550 kernel
      run:  |
        make clean && make mrproper
        export ARCH=arm64
        export BUILD_CROSS_COMPILE=$(pwd)/../PLATFORM/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export BUILD_JOB_NUMBER=`grep processor /proc/cpuinfo|wc -l`
        export ANDROID_MAJOR_VERSION=p
        export PLATFORM_VERSION=9.0.0
        mkdir out 
        chmod -R 777 out      
        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android  dream2qlte_chn_open_defconfig
        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android
      
    - name: Mod G9550 kernel
      run: |
        mv build/G9550.img build/boot.img
        build/unpackimg.sh build/boot.img
        mv build/boot.img build/G9550.img
        cp -R out/arch/arm64/boot/Image.gz-dtb build/split_img/
        rm -rf build/split_img/boot.img-zImage
        mv build/split_img/Image.gz-dtb build/split_img/boot.img-zImage
        sudo bash build/ramdisk.sh
        build/repackimg.sh
        mv build/image-new.img build/zip/boot.img
        build/cleanup.sh
        zip build/output/Neo-Kernel-SM_G9550.zip build/zip
        
    - name: Make G9500 kernel
      run:  |
        make clean && make mrproper
        export ARCH=arm64
        export BUILD_CROSS_COMPILE=$(pwd)/../PLATFORM/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export BUILD_JOB_NUMBER=`grep processor /proc/cpuinfo|wc -l`
        export ANDROID_MAJOR_VERSION=p
        export PLATFORM_VERSION=9.0.0


        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android  dreamqlte_chn_open_defconfig
        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android
      
    - name: Mod G9500 kernel
      run: |
        mv build/G9500.img build/boot.img
        build/unpackimg.sh build/boot.img
        mv build/boot.img build/G9500.img
        cp -R out/arch/arm64/boot/Image.gz-dtb build/split_img/
        rm -rf build/split_img/boot.img-zImage
        mv build/split_img/Image.gz-dtb build/split_img/boot.img-zImage
        sudo bash build/ramdisk.sh
        build/repackimg.sh
        mv build/image-new.img build/zip/boot.img
        build/cleanup.sh
        zip build/output/Neo-Kernel-SM_G9500.zip build/zip
        
    - name: Make N9500 kernel
      run:  |
        make clean && make mrproper
        export ARCH=arm64
        export BUILD_CROSS_COMPILE=$(pwd)/../PLATFORM/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-
        export BUILD_JOB_NUMBER=`grep processor /proc/cpuinfo|wc -l`
        export ANDROID_MAJOR_VERSION=p
        export PLATFORM_VERSION=9.0.0


        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android  greatqlte_chn_open_defconfig
        make -C $(pwd) O=$(pwd)/out -j$BUILD_JOB_NUMBER ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE KCFLAGS=-mno-android
      
    - name: Mod N9500 kernel
      run: |
        mv build/N9500.img build/boot.img
        build/unpackimg.sh build/boot.img
        mv build/boot.img build/N9500.img
        cp -R out/arch/arm64/boot/Image.gz-dtb build/split_img/
        rm -rf build/split_img/boot.img-zImage
        mv build/split_img/Image.gz-dtb build/split_img/boot.img-zImage
        sudo bash build/ramdisk.sh
        build/repackimg.sh
        mv build/image-new.img build/zip/boot.img
        build/cleanup.sh
        zip build/output/Neo-Kernel-SM_N9500.zip build/zip
      
    - uses: actions/upload-artifact@v3
      with:
        name: ALL-Model
        path: build/output/
        

      
